### PR TITLE
core: Add asynchronous components

### PR DESCRIPTION
**Pull request by AaronErhardt**
#### Summary

Add asynchronous components that run on the GLib main context.

#### Checklist

- [x] cargo fmt
- [x] cargo clippy
- [x] cargo test
- [x] updated CHANGES.md

### CODE REVIEW

**Comment by edfloreshz** [comment]
Can this be applied to Factory Components as well?

**Comment by edfloreshz** [comment]
Closes #342

**Review by edfloreshz — APPROVED** [review]
The changes look good to me, I tested them and everything looks fine. 

Great work 🎉

**Comment by edfloreshz** [comment]
I just realized that factories don't render anything inside async components.

**Comment by AaronErhardt** [comment]
> I just realized that factories don't render anything inside async components.

Can you provide an example for that?

**Comment by edfloreshz** [comment]
I was using a factory inside my component, once I turned into an async one the factory was no longer displayed. 

You can try to use the same factory in a sync and async component.

**Comment by AaronErhardt** [comment]
Ok, I'll try to modify the factory example to reproduce this.

**Comment by edfloreshz** [comment]
Okay, let me know if you can replicate this.

**Comment by AaronErhardt** [comment]
No, can't replicate. Switching to `SimpleAsyncComponent` in the factory example works just like the regular version.

**Comment by edfloreshz** [comment]
That's strange, I might be missing something then. In that case, I think it's safe to merge.

**Comment by AaronErhardt** [comment]
> That's strange, I might be missing something then. In that case, I think it's safe to merge.

I agree, let's merge this. We already have enough open PRs :sweat_smile: 
Also, factories and components might need some clean-ups anyway after the dust has settled on all the things happening currently.

**Pull request merged**
