### PR TITLE
all: Add CI job to check docs

### PR DESCRIPTION
**Pull request by AaronErhardt**
#### Summary

> The first commit should cause the CI to fail, it is just a test to verify that the current version fails to build

#### Checklist

- [x] cargo fmt
- [x] cargo clippy
- [x] cargo test
- [x] updated CHANGES.md

### CODE REVIEW

**Comment by AaronErhardt** [comment]
Also, disable nightly checks because apparently nightly clippy tends to be very pedantic and even throws errors on our dependencies. I think, we should disable nightly permanently now, it's just to tedious to handle.

**Comment by AaronErhardt** [comment]
@pentamassiv this PR fixes the dox feature of libpanel. If you want you can review it. Also, you might want to join the Relm4 organization so I can request reviews from you :)

**Comment by pentamassiv** [comment]
Sure, I believe you have to invite me to it, right?

**Review by pentamassiv — APPROVED** [review]
All good :)

**Review by pentamassiv — APPROVED** [review]
All good :)

**Pull request merged**
