### PR TITLE
Add an example how to use SimpleComboBox

### PR DESCRIPTION
**Pull request by marmistrz**
#### Summary
I found it not so easy to start using `SimpleComboBox` in my project (the book doesn't seem to explain much about injecting components into the view, the only examples I found were about dialogs, i.e., `#[local_ref]` is not really explained there).

So I created an example how to use it.

#### Checklist

- [x] cargo fmt
- [x] cargo clippy (unrelated lints in `bindings.rs`)
- [x] cargo test
- [x] updated CHANGES.md

### CODE REVIEW

**Comment by sgued** [comment]
Note that this is implemented in #534

**Comment by marmistrz** [comment]
Submitted 3 hours before! I'm fine with using either example, then.

**Comment by AaronErhardt** [comment]
First of all, thank you both @marmistrz and @sgued!

It's crazy, the timing couldn't have been worse. For months there was barely any example added and now there are two at the same time about the same feature.

To resolve the conflicting implementations, I suggest that we use this version of the combo box example for pure GTK and use (only) the libadwaita example of your version @sgued. Technically, the examples are both great. Yet, the GTK and libadwaita examples in #534 are almost identical, so I think using an example from another author simply adds just a little bit more value. Also, I like the idea of the language selector, which is a pretty realistic use-case.

**Review by AaronErhardt — APPROVED** [review]
Thanks!

**Pull request merged**
